#!/usr/bin/env bash
# a script that setup an nginx server
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/
sudo service nginx restart
