#!/usr/bin/env bash
# configure a redirection on Nginx server
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Redirected" > redirect_me
sudo mv redirect_me /var/www/html/
sudo cp /etc/nginx/sites-available/default ./
sudo sed -i "/:80 default_server;/a\
        rewrite ^/redirect_me shafam.com permanent;" default
sudo mv default /etc/nginx/sites-available/
sudo service nginx restart
