#!/usr/bin/env bash
# configure a redirection on Nginx server
#sudo apt-get -y install nginx
#ufw allow 'Nginx HTTP'
echo "Redirection of 301" > redirect_me
sudo mv redirect_me /var/www/html/
sudo sed -i '/:80 default_server;/a\
        rewrite ^/redirect_me shafam.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
