#!/usr/bin/env bash
# a script that setup nginx server and added a custom header
if ! command nginx &> /dev/null; then
	sudo apt update
	sudo apt -y install nginx
fi
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/
sudo sed -i '0,/try_files $uri $uri\/ =404;/s/try_files $uri $uri\/ =404;/try_files $uri $uri\/ =404; \n add_header X-Served-By "$hostname";/' /etc/nginx/sites-available/default
sudo service nginx restart
