#!/usr/bin/env bash
# a script that install a load balancer
if ! command haproxy &> /dev/null; then
	sudo apt update
	sudo apt -y install haproxy
fi
sudo sed -i '$a\ENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg{,.original}
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 525397-web-01 3.94.86.136:80 check
    server 525397-web-02 54.227.89.138:80 check
EOF

sudo service haproxy start
