#!/usr/bin/env bash
# a script that install a load balancer
sudo apt update
if ! command -v haproxy &> /dev/null; then
    sudo apt -y install haproxy
fi
if ! grep -q '^ENABLED=1$' /etc/default/haproxy; then
    sudo sed -i '$a\ENABLED=1' /etc/default/haproxy
fi
sudo cp /etc/haproxy/haproxy.cfg{,.original}
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 525397-web-01 100.26.210.231:80 check
    server 525397-web-02 54.172.119.166:80 check
EOF
sudo service restart haproxy
sudo systemctl restart haproxy
