#!/usr/bin/env bash
# setup web server for ufw on ports to allow
if ! command -v ufw &> /dev/null; then
	sudo apt update
	sudo apt install -y ufw
fi

ufw allow 22
ufw allow 443
ufw allow 80
ufw default deny incoming
ufw enable
